import { formatNaira } from "@/lib/utils";

type InvoicePdfInput = {
  invoiceNumber: string;
  status: string;
  createdAt: Date;
  dueDate: Date;
  subtotal: number;
  discountAmount: number;
  total: number;
  amountPaid: number;
  notes?: string | null;
  store: {
    name: string;
    ownerName?: string | null;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    branchName?: string | null;
    bankName?: string | null;
    bankAccountNumber?: string | null;
    bankAccountName?: string | null;
  };
  customer: {
    name: string;
    phone: string;
    customerId?: string | null;
  };
  items: Array<{
    name: string;
    quantity: number;
    unitPrice: number;
    totalPrice: number;
  }>;
};

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const LEFT = 48;
const RIGHT = 547;

export function invoicePdfFilename(invoiceNumber: string): string {
  return `${invoiceNumber.replace(/[^A-Za-z0-9_-]+/g, "-")}.pdf`;
}

export function generateInvoicePdf(input: InvoicePdfInput): Buffer {
  const lines: string[] = [];
  let y = 790;

  function text(value: string, x: number, size = 10, font = "F1") {
    lines.push(`BT /${font} ${size} Tf ${x} ${y} Td (${escapePdf(value)}) Tj ET`);
    y -= Math.round(size * 1.45);
  }

  function row(label: string, value: string, size = 10) {
    lines.push(`BT /F1 ${size} Tf ${LEFT} ${y} Td (${escapePdf(label)}) Tj ET`);
    const estimatedWidth = value.length * size * 0.48;
    lines.push(`BT /F2 ${size} Tf ${Math.max(LEFT + 180, RIGHT - estimatedWidth)} ${y} Td (${escapePdf(value)}) Tj ET`);
    y -= Math.round(size * 1.5);
  }

  function gap(amount = 12) {
    y -= amount;
  }

  function rule() {
    lines.push(`${LEFT} ${y} m ${RIGHT} ${y} l S`);
    y -= 16;
  }

  lines.push("0.79 0.66 0.38 rg 48 804 499 3 re f");
  text(input.store.name, LEFT, 22, "F2");
  text("Invoice", LEFT, 18, "F2");
  y = 770;
  row("Invoice number", input.invoiceNumber, 11);
  row("Status", labelStatus(input.status), 11);
  row("Issued", formatDate(input.createdAt), 10);
  row("Due", formatDate(input.dueDate), 10);
  rule();

  text("Vendor / Store Details", LEFT, 13, "F2");
  row("Store", input.store.name);
  if (input.store.ownerName) row("Owner", input.store.ownerName);
  if (input.store.branchName) row("Branch", input.store.branchName);
  if (input.store.address) {
    for (const line of wrap(`Address: ${input.store.address}`, 86)) text(line, LEFT, 9);
  }
  if (input.store.phone) row("Phone", input.store.phone);
  if (input.store.email) row("Email", input.store.email);
  if (input.store.bankName || input.store.bankAccountNumber || input.store.bankAccountName) {
    row("Payment account", [input.store.bankName, input.store.bankAccountNumber, input.store.bankAccountName].filter(Boolean).join(" / "));
  }
  gap(8);

  text("Customer Details", LEFT, 13, "F2");
  row("Customer", input.customer.name);
  row("WhatsApp", input.customer.phone);
  if (input.customer.customerId) row("Customer ID", input.customer.customerId);
  rule();

  text("Items", LEFT, 13, "F2");
  row("Description", "Qty   Unit Price   Total", 9);
  gap(2);
  for (const item of input.items) {
    const name = wrap(item.name, 48)[0] ?? item.name;
    lines.push(`BT /F1 10 Tf ${LEFT} ${y} Td (${escapePdf(name)}) Tj ET`);
    const summary = `${item.quantity}   ${formatNaira(item.unitPrice)}   ${formatNaira(item.totalPrice)}`;
    lines.push(`BT /F1 10 Tf ${RIGHT - summary.length * 4.7} ${y} Td (${escapePdf(summary)}) Tj ET`);
    y -= 17;
  }
  rule();

  row("Subtotal", formatNaira(input.subtotal), 11);
  if (input.discountAmount > 0) row("Discount", `- ${formatNaira(input.discountAmount)}`, 11);
  row("Total", formatNaira(input.total), 13);
  if (input.amountPaid > 0) row("Paid", `- ${formatNaira(input.amountPaid)}`, 11);
  row("Balance due", formatNaira(Math.max(0, input.total - input.amountPaid)), 13);

  if (input.notes) {
    gap(8);
    text("Notes", LEFT, 12, "F2");
    for (const line of wrap(input.notes, 88).slice(0, 5)) text(line, LEFT, 9);
  }

  y = 48;
  text("Generated by Vodium Ledger. Please contact the vendor if anything on this invoice looks wrong.", LEFT, 8);

  const content = lines.join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    `<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index < offsets.length; index++) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  return Buffer.from(pdf, "utf8");
}

function escapePdf(value: string): string {
  return value.replace(/[\\()]/g, "\\$&").replace(/[^\x20-\x7E]/g, " ");
}

function wrap(value: string, max: number): string[] {
  const words = value.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > max && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [value];
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" });
}

function labelStatus(status: string): string {
  return status.replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
}
