-- Per-installment balances and reminder idempotency.
ALTER TABLE "RepaymentSchedule"
  ADD COLUMN IF NOT EXISTS "amountPaid" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "reminderSentAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "overdueReminderSentAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "RepaymentSchedule_reminderSentAt_idx"
  ON "RepaymentSchedule"("reminderSentAt");
CREATE INDEX IF NOT EXISTS "RepaymentSchedule_overdueReminderSentAt_idx"
  ON "RepaymentSchedule"("overdueReminderSentAt");

ALTER TYPE "WhatsAppState" ADD VALUE IF NOT EXISTS 'ADDING_INSTALLMENT_CUSTOMER';
ALTER TYPE "WhatsAppState" ADD VALUE IF NOT EXISTS 'ADDING_INSTALLMENT_PHONE';
ALTER TYPE "WhatsAppState" ADD VALUE IF NOT EXISTS 'ADDING_INSTALLMENT_AMOUNT';
ALTER TYPE "WhatsAppState" ADD VALUE IF NOT EXISTS 'ADDING_INSTALLMENT_DOWN_PAYMENT';
ALTER TYPE "WhatsAppState" ADD VALUE IF NOT EXISTS 'ADDING_INSTALLMENT_COUNT';
ALTER TYPE "WhatsAppState" ADD VALUE IF NOT EXISTS 'ADDING_INSTALLMENT_SCHEDULE';
ALTER TYPE "WhatsAppState" ADD VALUE IF NOT EXISTS 'ADDING_INSTALLMENT_CONFIRM';
