"use client";
import { useEffect, useState } from "react";
import { Newspaper, Plus, Save, Trash2, X } from "lucide-react";

type Post = { id: string; slug: string; title: string; excerpt: string; content: string; category: string; authorName: string; coverImageUrl: string | null; status: "DRAFT" | "PUBLISHED"; publishedAt: string | null };
const empty = { title: "", excerpt: "", content: "", category: "NEWS", authorName: "", coverImageUrl: "", status: "DRAFT" as const, slug: "" };
const input = "input-dark w-full rounded-lg px-3 py-2 text-sm";

export function NewsAdmin() {
  const [posts, setPosts] = useState<Post[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const res = await fetch("/api/admin/news"); const data = await res.json(); if (res.ok) setPosts(data.posts); }
  useEffect(() => { load(); }, []);
  function set(key: string, value: string) { setForm((f) => ({ ...f, [key]: value })); }
  function edit(post: Post) { setEditing(post.id); setShowForm(true); setForm({ ...post, coverImageUrl: post.coverImageUrl ?? "", slug: post.slug }); setError(""); }
  function reset() { setEditing(null); setShowForm(false); setForm(empty); setError(""); }
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const res = await fetch(editing ? `/api/admin/news/${editing}` : "/api/admin/news", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, coverImageUrl: form.coverImageUrl || null }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); reset(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save post"); } finally { setBusy(false); } }
  async function remove(id: string) { if (!window.confirm("Delete this post?")) return; await fetch(`/api/admin/news/${id}`, { method: "DELETE" }); if (editing === id) reset(); load(); }
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-serif text-2xl text-vodium-cream flex items-center gap-2"><Newspaper size={20} className="text-vodium-gold" /> News &amp; blog</h1><p className="text-sm text-vodium-cream/40 mt-1">Create search-friendly updates and publish them to the public website.</p></div><button onClick={() => { setEditing(null); setForm(empty); setShowForm(true); }} className="btn-gold inline-flex items-center gap-2 text-xs rounded-lg px-3 py-2"><Plus size={14} /> New post</button></div>
    {showForm && <form onSubmit={save} className="rounded-2xl border border-white/[0.08] bg-vodium-charcoal p-5 space-y-4"><div className="flex justify-between"><h2 className="font-serif text-xl text-vodium-cream">{editing ? "Edit post" : "New post"}</h2><button type="button" onClick={reset} className="text-vodium-cream/40"><X size={16}/></button></div>{error && <p className="text-sm text-rose-300">{error}</p>}<div className="grid md:grid-cols-2 gap-3"><Field label="Title" value={form.title} onChange={(v) => set("title", v)} /><Field label="Category" value={form.category} onChange={(v) => set("category", v)} /><Field label="Author" value={form.authorName} onChange={(v) => set("authorName", v)} /><Field label="Slug (optional)" value={form.slug} onChange={(v) => set("slug", v)} /><Field label="Cover image URL (optional)" value={form.coverImageUrl} onChange={(v) => set("coverImageUrl", v)} /><label className="text-xs text-vodium-cream/50">Status<select value={form.status} onChange={(e) => set("status", e.target.value as "DRAFT" | "PUBLISHED")} className={`${input} mt-1`}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label></div><Field label="Excerpt" value={form.excerpt} onChange={(v) => set("excerpt", v)} textarea /><Field label="Article content" value={form.content} onChange={(v) => set("content", v)} textarea /><p className="text-[11px] text-vodium-cream/30">Content supports plain text paragraphs. Use a blank line between paragraphs.</p><button disabled={busy} className="btn-gold inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm"><Save size={14}/>{busy ? "Saving…" : form.status === "PUBLISHED" ? "Save & publish" : "Save draft"}</button></form>}
    <div className="space-y-3">{posts.length === 0 ? <p className="text-sm text-vodium-cream/35 py-6">No posts yet.</p> : posts.map((post) => <div key={post.id} className="rounded-xl border border-white/[0.06] bg-vodium-charcoal p-4 flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-medium text-vodium-cream">{post.title}</h3><span className={`text-[10px] uppercase tracking-wider px-2 py-1 rounded border ${post.status === "PUBLISHED" ? "text-emerald-300 border-emerald-400/20 bg-emerald-400/10" : "text-vodium-cream/40 border-white/10"}`}>{post.status}</span></div><p className="text-xs text-vodium-cream/35 mt-1">/{post.slug} · {post.category} · {post.authorName}</p></div><div className="flex gap-2"><button onClick={() => edit(post)} className="text-xs border border-white/[0.08] rounded-lg px-3 py-2 text-vodium-cream/60 hover:text-vodium-gold">Edit</button><button onClick={() => remove(post.id)} className="text-vodium-cream/35 hover:text-rose-300 p-2" aria-label="Delete post"><Trash2 size={15}/></button></div></div>)}</div>
  </div>;
}
function Field({ label, value, onChange, textarea = false }: { label: string; value: string; onChange: (v: string) => void; textarea?: boolean }) { return <label className={`text-xs text-vodium-cream/50 ${textarea ? "block" : ""}`}>{label}{textarea ? <textarea required value={value} onChange={(e) => onChange(e.target.value)} className={`${input} mt-1 min-h-24`} /> : <input required={label !== "Slug (optional)" && !label.includes("Cover")} value={value} onChange={(e) => onChange(e.target.value)} className={`${input} mt-1`} />}</label>; }
